take 6

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -141,15 +141,16 @@ jobs:
     if: always() # Always run so that we never skip this check
     needs: check-tests
       # Pass only if check-tests set its output value
-    run: |
-      PASSED="${{ needs.check-tests.outputs.success }}"
-      if [[ $PASSED == "true" ]]; then
-        echo "All tests passed!"
-        exit 0
-      else
-        echo "One or more tests FAILED!"
-        exit 1
-      fi
+    steps:
+      run: |
+        PASSED="${{ needs.check-tests.outputs.success }}"
+        if [[ $PASSED == "true" ]]; then
+          echo "All tests passed!"
+          exit 0
+        else
+          echo "One or more tests FAILED!"
+          exit 1
+        fi
 
   # sbt ci-release publishes all cross versions so this job needs to be
   # separate from a Scala versions build matrix to avoid duplicate publishing
